algae_project/algae_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^blank/$', views.blank, name='blank'),
	url(r'^images/$', views.images, name='images'),
	url(r'^water/$', views.water, name='water'),
	url(r'^prediction/$', views.prediction, name='prediction'),
	url(r'^recalls/$', views.RecallListView.as_view(), name='recall-list'),
]

algae_project/algae_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from algae_app import views

admin.site.site_header = 'Algae Admin'
admin.site.site_title = 'Algae Admin'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^algae/', include('algae_app.urls', namespace="algae") ),
    url(r'^$', views.water, name='home'),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG is True:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

algae_project/algae_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

from django.db import models
from django.core.files.storage import FileSystemStorage

#fs = FileSystemStorage(location='/media/photos')

class RawImage(models.Model):
    img = models.ImageField(upload_to='img')
    source = models.CharField(max_length=15, blank=True, null=True)
    description = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

class RecallImage(models.Model):
	img = models.ImageField(upload_to='img')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	raw = models.ForeignKey("RawImage", on_delete=models.CASCADE)
	algae_pixel=models.IntegerField(default=0)

class Count(models.Model):
	recall = models.ForeignKey("RecallImage", on_delete=models.CASCADE)
	obj_type= models.ForeignKey("ObjType", on_delete=models.CASCADE)
	obj_count = models.IntegerField(default=0)

class ObjType(models.Model):
	description = models.CharField(max_length=20, blank=True, null=True)

class LabelImage(models.Model):
	img = models.ImageField(upload_to='img')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	raw = models.ForeignKey("RawImage", on_delete=models.CASCADE)

algae_project/algae_app/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import RecallImage
# Create your views here.
def blank(request): 
	return render(request,'blank.html', 
		{
			'title':'blank'
		})

def images(request): 
	return render(request,'images.html', 
		{
			'title':'images'
		})

def water(request): 
	return render(request,'water.html', 
		{
			'title':'water'
		})

def prediction(request): 
	return render(request,'prediction.html', 
		{
			'title':'prediction'
		})

class RecallListView(ListView):
    model = RecallImage
    template_name = 'recall_list.html'  # Default: <app_label>/<model_name>_list.html
    #context_object_name = 'recalls'  # Default: object_list
    paginate_by = 5
    queryset = RecallImage.objects.all()  # Default: Model.objects.all()

algae_project/algae_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<meta charset="utf-8">
<html lang="en">
<head>
  {% block head %}{% endblock head %}
  <title>{{title}}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <script src="{% static 'jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap.min.js' %}" ></script>
</head>
<body style="height:1024px, height:1024px">

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'algae:water' %}">Algae Monitoring and Prediction</a>
    </div>
    <ul class="nav navbar-nav">
      <!--li id="prediction"><a href="{% url 'algae:prediction' %}">Prediction</a></li-->
      <li id="water"><a href="{% url 'algae:water' %}">Water History</a></li>
      <li id="images"><a href="{% url 'algae:recall-list' %}">Images</a></li>
    </ul>
  </div>
</nav>
  
<div class="container" style="margin-top:0px">
{% block content %}{% endblock content %}
</div>
</body>
{% block script %}{% endblock script %}
</html>

algae_project/algae_app/templates/blank.html
<h3>Fixed Navbar</h3>
<div class="row">
  <div class="col-md-4">
    <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p>
    <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p>    
  </div>
  <div class="col-md-4"> 
    <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p>
    <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p>
  </div>
  <div class="col-md-4"> 
    <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p>
    <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p> 
  </div>
</div>

algae_project/algae_app/templates/images.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h3>Fixed Navbar</h3>
<div class="row">
  <div class="col-md-4">
    <img src="{% static 'graph.png' %}" class="img-rounded" alt="water property" width="640" height="480"> 
  </div>
  <div class="col-md-4"> 
    <img src="{% static 'graph.png' %}" class="img-rounded" alt="water property" width="640" height="480"> 
  </div>
  <div class="col-md-4"> 
    <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p>
    <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p> 
  </div>
</div>
{% endblock content %}

{% block script %}
<script>
  $('#images').addClass('active');
</script>
{% endblock script %}

algae_project/algae_app/templates/prediction.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<style>

.axis--x path {
  display: none;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 1.5px;
}

</style>
{% endblock head %}{% block content %}

<h3>Fixed Navbar</h3>
<div class="row">
  <div class="col-md-12">
    <svg width="960" height="500"></svg>
  </div>
</div>
<div class="row">
  <div class="col-md-8"> 
    <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p>
    <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p> 
  </div>
  <div class="col-md-4"> 
    <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p>
    <p>A fixed navigation bar stays visible in a fixed position (top or bottom) independent of the page scroll.</p> 
  </div>
</div>
{% endblock content %}

{% block script %}
<script>
  $('#prediction').addClass('active');
</script>
<script src="{% static 'd3.v4.min.js' %}"></script>
<script>
var svg = d3.select("svg"),
    margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = svg.attr("width") - margin.left - margin.right,
    height = svg.attr("height") - margin.top - margin.bottom;

var parseDate = d3.timeParse("%Y %b %d");

var x = d3.scaleTime().range([0, width]),
    y = d3.scaleLinear().range([height, 0]),
    z = d3.scaleOrdinal(d3.schemeCategory10);

var stack = d3.stack();

var area = d3.area()
    .x(function(d, i) { return x(d.data.date); })
    .y0(function(d) { return y(d[0]); })
    .y1(function(d) { return y(d[1]); });

var g = svg.append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

d3.tsv("{% static 'data.tsv' %}", type, function(error, data) {
  if (error) throw error;

  var keys = data.columns.slice(1);

  x.domain(d3.extent(data, function(d) { return d.date; }));
  console.log(JSON.stringify(
      d3.extent(data, function(d) { return d.date; })
    ));
  z.domain(keys);
  console.log(JSON.stringify(
      keys
    ));
  stack.keys(keys);

  var layer = g.selectAll(".layer")
    .data(stack(data))
    .enter().append("g")
      .attr("class", "layer");

  layer.append("path")
      .attr("class", "area")
      .style("fill", function(d) { return z(d.key); })
      .attr("d", area);

  layer.filter(function(d) { return d[d.length - 1][1] - d[d.length - 1][0] > 0.01; })
    .append("text")
      .attr("x", width - 6)
      .attr("y", function(d) { return y((d[d.length - 1][0] + d[d.length - 1][1]) / 2); })
      .attr("dy", ".35em")
      .style("font", "10px sans-serif")
      .style("text-anchor", "end")
      .text(function(d) { return d.key; });

  g.append("g")
      .attr("class", "axis axis--x")
      .attr("transform", "translate(0," + height + ")")
      .call(d3.axisBottom(x));

  g.append("g")
      .attr("class", "axis axis--y")
      .call(d3.axisLeft(y).ticks(10, "%"));
});

function type(d, i, columns) {
  d.date = parseDate(d.date);
  for (var i = 1, n = columns.length; i < n; ++i) d[columns[i]] = d[columns[i]] / 100;
  return d;
}
</script>
</script>
{% endblock script %}

algae_project/algae_app/templates/recall_list.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<style>
.fill { 
    min-height: 100%;
    height: 100%;
}
</style>
{% endblock head %}


{% block content %}
<h1>Algae Detection</h1>

<div class="container">
  
  {% for i in object_list %}
    
      <div class="row">
        <div class="col-md-4">
          <div class="row">
            <img src="{{ i.raw.img.url }}" class="img-rounded" alt="water property" width="320" height="240">
          </div>
          <div class="row">
            raw: {{ i.raw.img.name }}
          </div>
        </div>
        <div class="col-md-4"> 
          <div class="row">
            <img src="{{ i.img.url }}" class="img-rounded" alt="water property" width="320" height="240">
          </div>
          <div class="row">
            detection: {{ i.img.name }}
          </div>
        </div>
        <div class="col-md-4">
          <div class="row fill">
            <div class="panel panel-default fill">
              <div class="panel-body ">
                <p>
                  created: {{ i.raw.created }}
                  <br>updated: {{ i.updated }}
                  <br>detected pixels: {{ i.algae_pixel }}
                  <br>Aulocoseria sp.: 1
                </p>
              </div>
            </div>
            
          </div>
          
        </div>
      </div>
    
  {% endfor %}
  
  
</div>


{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}






{% endblock content %}

{% block script %}
<script>
  $('#images').addClass('active');
</script>
{% endblock script %}

algae_project/algae_app/templates/water.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h3>Water Property History</h3>
<div class="container">
             
  <img src="{% static 'graph.png' %}" class="img-rounded" alt="water property" width="960" height="960"> 
</div>
<div class="row">
  <div class="col-md-6">
    <p>The data is collected by <a href="http://www.mwa.co.th/">MWA</a> including chemical and biological information between 2012 and 2015. Algal bloom occurs about once a year and tends to be more often and larger in magnitude this caused by waste water discarging from city and heavily use of fertilizer in agricultural processes.
    </p>
       
  </div>
  <div class="col-md-6"> 
    <p>
      From our preliminary investigation, conductiveity is over 500umho/cm and turbidity lower than 400 NTU can be used as primary indicator for predicting the algal bloom.</p> 
  </div>
</div>
{% endblock content %}

{% block script %}
<script>
  $('#water').addClass('active');
</script>
{% endblock script %}